name: release flannel and upload docker images
  
on:
  release:
    types: [published]

env:
  GO_VERSION: "1.21"
  LINUX_ARCHES: "ppc64le"
  REPOSITORY: rahulssv/flannel

jobs:
  build-and-push-images:
    runs-on: ubuntu-20.04-ppc64le
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set tag 
        run: echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          architecture: ${{ env.LINUX_ARCHES }}

      - name: go mod vendor
        run: go mod vendor

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }}
          flavor: latest=false
          tags: |
            type=ref,event=tag

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: github.repository_owner == 'flannel-io' && success()
        uses: docker/build-push-action@v3
        with:
          context: .
          file: images/Dockerfile
          push: true
          platforms: linux/ppc64le
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TAG=${{ env.GIT_TAG }}

  build-and-push-artifacts:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-20.04-ppc64le
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          architecture: ${{ env.LINUX_ARCHES }}

      - name: go mod vendor
        run: go mod vendor

      - name: Setup make
        run: sudo apt install -qy make

      - name: Build release artifacts
        run: make release

      - name: Upload release files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/flannel*
            dist/kube-flannel.yml
            dist/kube-flannel-psp.yml

      - name: Wait for previous job
        uses: yogeshlonkar/wait-for-jobs@v0.2.1
        with:
          jobs: build-and-push-images

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'chart/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
